// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/bbq-menu-categories/Current.tsx": () => import("../components/mockups/bbq-menu-categories/Current.tsx"),
  "./components/mockups/bbq-menu-categories/Refined.tsx": () => import("../components/mockups/bbq-menu-categories/Refined.tsx")
};
